import { type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <h2>Hello it's me mario</h2>
        <button className="btn" onClick={() => signIn()}>Sign In</button>
      </main>
    </>
  );
};

export default Home;
