import type { GetServerSideProps, NextPage } from "next";
import { getSession, signIn } from "next-auth/react";

import Head from "next/head";

const Home: NextPage = () => {
  const handleSigningIn = () => {
    void signIn();
  };

  return (
    <>
      <Head>
        <title>PixelPerfect</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <button className="btn" onClick={handleSigningIn}>
          Hay Bro You need to login first Click here baby
        </button>
      </main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getSession(ctx);
  if (session)
    return {
      props: {},
      redirect: {
        destination: "/",
      },
    };

  return {
    props: {},
  };
};

export default Home;
